---
repos:

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.23.0
    hooks:
      - id: yamllint

  - repo: https://github.com/igorshubovych/markdownlint-cli.git
    rev: v0.23.1
    hooks:
      - id: markdownlint

  - repo: https://github.com/motet-a/jinjalint
    rev: master
    hooks:
      - id: jinjalint

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: master  # or specific git tag
    hooks:
      - id: forbid-binary
        exclude: (\.ico|\.mqproj)$
      - id: git-check     # Configure in .gitattributes
      # - id: markdownlint  # Configure in .mdlrc.style.rb
      # - id: require-ascii

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: \.txt$
      - id: trailing-whitespace
        exclude: \.txt$

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args: [--line-length=88]
        files: '(\.py)$'

  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        # Harmonizing flake8 and black
        args: [--max-line-length=88]
        files: '(\.py)$'
