# yamllint disable rule:line-length
---
name: Lint
on:
  - pull_request
  - push
jobs:
  YAML:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: YAML check (yamllint)
        uses: ibiqlik/action-yamllint@master
        with:
          strict: true
  MQL:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: DoozyX/clang-format-lint-action@v0.5
        with:
          extensions: 'h'
